Programación para la ciencia de datos - PEC1
============================

En este Notebook encontraréis un conjunto de ejercicios que conforman la primera actividad de evaluación continua (PAC) de la asignatura.

Para cada ejercicio, tened en cuenta que:  

* **Es necesario incluir comentarios** de vuestro código, que expliquen cómo ha implementado la solución del problema planteado.  
* **Es imprescindible** citar las referencias consultadas para realizar la actividad. Se valorará que el código proporcionado solucione el problema propuesto y también la calidad del código (comentarios, legibilidad, claridad, uso de las estructuras de datos adecuadas, buena nomenclatura de las variables y funciones, seguimiento del PEP8, etc. ).

Veréis que cada una de las actividades tiene asociada una puntuación, que indica el peso que tiene la actividad sobre la nota de la PAC.

Además, todas las actividades tienen una etiqueta, que indica los recursos necesarios para llevarla a cabo. Hay tres posibles etiquetas:
* <span style="font-family: Courier New; background-color: #82b74b; color: #000000; padding: 3px; ">SM</span>   **Sólo materiales**: las herramientas necesarias para realizar la actividad se pueden encontrar en los materiales de la asignatura (consideraremos también los materiales de la asignatura Fundamentos de Programación, así como las lecturas obligatorias de material externo que se indican en los notebooks).  
* <span style="font-family: Courier New; background-color: #ffcc5c; color: #000000; padding: 3px; ">EG</span>**Consulta externa guiada**: la actividad puede requerir hacer uso de herramientas que no se encuentran en los materiales de la asignatura, pero el enunciado contiene indicaciones de dónde o cómo encontrar la información adicional necesaria para resolver la actividad.  
* <span style="font-family: Courier New; background-color: #f2ae72; color: #000000; padding: 3px; ">EI</span>**Consulta externa independiente**: la actividad puede requerir hacer uso de herramientas que no se encuentran en los materiales de la asignatura, y el enunciado puede no incluir la descripción de dónde o cómo encontrar esta información adicional. Será necesario que el estudiante busque esta información utilizando los recursos que se han explicado en la asignatura.

Es importante notar que estas etiquetas no indican el nivel de dificultad del ejercicio, sino únicamente la necesidad de consulta de documentación externa para su resolución. Además, recuerde que las **etiquetas son informativas**, pero puede consultar referencias externas siempre que lo desee (aunque no se indique explícitamente) o puede que pueda realizar una actividad sin consultar ningún tipo de documentación. Por ejemplo, para resolver una actividad que sólo requiera los materiales de la asignatura, puede consultar referencias externas si se desea, ya sea tanto para ayudar en la resolución como para ampliar conocimientos.


---

## Antes de empezar

Leed atentamente los parágrafos que siguen, relacionados con la originalidad en las actividades, antes de empezar a trabajar en la PEC. Si os surge cualquier duda dirigiros al profesor colaborador de la asignatura antes de continuar con la actividad.

<div class="alert alert-block alert-success"> La falta de originalidad se produce cuando en una actividad aparece contenido que no ha sido elaborado de forma individual por el estudiante y no se referencia adecuadamente su origen. O bien cuando, aunque el contenido externo esté referenciado, este es tan extenso que no es posible considerar al estudiante el autor o autora de la actividad.
<br /><br />
Así, algunos ejemplos de comportamientos inadecuados debido a falta de originalidad son:
<ol>
    <li>Crear la solución de un ejercicio de la PEC en colaboración entre diversos estudiantes.</li>
    <li>Incluir un ejercicio de la PEC que utiliza código encontrado en internet sin citar la fuente.</li>
    <li>Compartir vuestra solución de la PEC con otros estudiantes de la asignatura.</li>
    </ol>
</div>

## Instrucciones de entrega

Para proceder a la entrega de la actividad es necesario realizar los siguientes pasos:

1. Comprobad que el notebook se ejecuta correctamente en Google Colaboratory. Es importante que antes de entregar vuestra PEC os aseguréis que la versión final del código ejecuta correctamente en su totalidad. Para ello, se recomienda hacer una ejecución completa desde cero del notebook haciendo click en <i>"Entorno de ejecución y ejecutar todas",</i> y comprobando que todas las celdas del notebook se ejecutan correctamente.
2. Confirmad que sois los autores únicos de la PEC y que esta incluye todas las citas a recursos externos que se hayan utilizado para elaborarla. Con el fin de confirmar que sois los autores únicos de la actividad, añadid vuestro nombre completo en la celda siguiente.
3. Entregad el notebook correspondiente a la resolución de la PEC a través del Registro de Evaluación Continua del aula. Podéis descargar el notebook mediante <i> "Archivo, descargar y descargar .ipynb" </i>

<div class="alert alert-block alert-warning">Yo, **Aleem Karim Saeed**, confirmo que he elaborado de forma individual todas las actividades resueltas en esta PEC y que he incluido las citas a todas las fuentes externas que he utilizado para resolver las actividades. </div>


## Type hints

Os recomendamos resolver esta PEC usando type hints. Podemos entender los type hints de Python como una solución formal para indicar estéticamente el tipo de valor dentro del código Python. Os recomendamos la visualización del siguiente [vídeo](https://www.youtube.com/watch?v=j0dy8Q9VIPk) para una introducción a los type hints en Python, y para entender por qué son interesantes.

##  Enunciado
Los siguientes ejercicios se realizarán utlilizando el dataset denuncies_sancions.csv proporcionado juntamente con la PEC, y que contiene información sobre diferentes sanciones de tráfico en la ciudad de Barcelona, obtenido de la web de Open Data del Ayuntamiento de Barcelona. Cada fila representa una sanción.

Los campos del dataset son los siguientes:

   - Infraccio_codi: Código interno de la infracción.
   - Infraccio_Desc_Curta_CA: Descripción corta de la infracción en catalán.
   - Infraccio_Desc_Curta_ES: Descripción corta de la infracción en español.
   - Infraccio_Desc_Llarga_ES: Descripción detallada de la infracción en español.
   - Data_Inici_Vigencia: Fecha aplicación de la sanción.
   - Data_Fi_Vigencia: Fecha fin de la vigencia de la sanción (por defecto, siempre 31/12/9999)
   - Article: Código del artículo legal por el cual se aplica la sanción.
   - Normativa: Procedencia de la normativa del cual procede el artículo.
   - Import_Nominal_?: Importe de la sanción.
   - Tipus_Infraccio: Código del tipo de infracción.
   - Punts_A_Retirar: Puntos a retirar al conductor.
   - Autoritat: Autoridad que firma la sanción


**IMPORTANTE:** La carga del dataset se debe hacer usando **rutas relativas**, tenéis que cargar el fichero teniendo en cuenta que trabajáis (vuestro notebook se encuentra) en una carpeta que contiene la carpeta *data* y el archivo de datos correspondiente.


Sólo tenéis que cargar el fichero una sola vez en el primer ejercicio.

## Ejercicio 1

Cargad el dataset de forma que obtengáis un objecto de tipo dataframe.

Una vez cargado el dataset resuelve las siguientes questiones:

1. Visualiza los primeros 90 registros.
2. Devuelve el número de diferentes descripciones de sanciones en catalán.
3. Convertir la columna de fecha de inicio de la sanción al formato Dia/Mes/Año (dd/mm/aaaa).
4. Comprueba que todos los valores de fin de vigencia son iguales. En caso afirmativo, elimina la columna.
5. Visualiza la sanción con el importe más elevado.
6. Modifica el título de la columna "Infraccio_Codi" por "Codi"

Pista 1: Recordad qude podéis utilizar librerías como 'pandas' para cargar el conjunto de datos de forma sencilla y obtener un dataframe.

Pista 2: El type hint de un dataframe es pd.DataFrame.

**Todos los ejercicios se tienen que resolver a partir del dataframe obtenido al finalizar este ejercicio y no cargarlo cada vez que se deba utilizar.**

<span style="font-family: Courier New; background-color: #82b74b; color: #000000; padding: 3px; ">SM</span> **(2 puntos)**

<div style="background-color: #fcf2f2; border-color: #dfb5b4; border-left: 5px solid #dfb5b4; padding: 0.5em;">
<strong>Solución</strong>
</div>

In [116]:
from google.colab import drive

# Montamos Google Drive
drive.mount('/content/drive')

# Importamos pandas y cargamos el archivo CSV especificando la codificación y
# delimitador, y cargamos el dataset en un dataframe usando 'latin1' como
# codificación y ';' como delimitador
import pandas as pd
data = pd.read_csv('/content/drive/My Drive/Colab_Notebooks/Programación_DS/Activity_1/data/denuncies_sancions.csv', encoding='latin1', sep=';')

# 1. Visualisamos los primeros 90 registros para testear si los datos se han
# cargado correctamente. Para ello, es suficiente con poner 90 directamente
# aunque el último registro sea el número 89 ya que la enumeración comienza
# con 0.
data.head(90)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

,Infraccio_Codi,Infraccio_Desc_Curta_CA,Infraccio_Desc_Curta_ES,Infraccio_Desc_Llarga_CA,Infraccio_Desc_Llarga_ES,Data_Inici_Vigencia,Data_Fi_Vigencia,Article,Normativa,Import_Nominal_?,Tipus_Infraccio,Punts_A_Retirar,Autoritat
0,910,NO IDENTIFIC CONDUCT RESPONS INFRACCIO,NO IDENTIFIC CONDUCT RESPONS INFRACCION,NaN,-,2005-03-16,9999-12-31,77. J,LSV,301,E,0,Il.lm./a Sr./a Regidor/a del Districte
1,912,NO IDENTIFICAR EL CONDUCTOR RESPONSABLE DE LA ...,NO IDENTIFICAR AL CONDUCTOR RESPONSABLE DE LA ...,NaN,-,1900-01-03,9999-12-31,77. J,LSV,301,E,0,Il.lm./a Sr./a Regidor/a del Districte
2,913,NO IDENTIFICAR EL CONDUCTOR RESPONSABLE DE LA ...,NO IDENTIFICAR AL CONDUCTOR RESPONSABLE DE LA ...,NaN,-,1900-01-03,9999-12-31,77. J,LSV,1000,E,0,Il.lm./a Sr./a Regidor/a del Districte
3,1001,INSTAL SENYAL V PUB SENSE PERMIS O CAUSA,INSTAL SENAL V PUBL SIN PERMISO O CAUSA,Instal.lar senyalitzacio en una via publica se...,-,2003-05-21,9999-12-31,73.C A,OCVV,90,E,0,Il.lm./a Sr./a Regidor/a del Districte
4,1002,COL.LOC SOBRE SENYAL/COSTAT OBJ PUBLICIT,COLOCAR SOBRE SENAL/LADO OBJETO PUBLICIT,Col.locar publicitat a sobre o al costat dels ...,-,2003-05-21,9999-12-31,73.B A,OCVV,90,E,0,Il.lm./a Sr./a Regidor/a del Districte
...,...,...,...,...,...,...,...,...,...,...,...,...,...
85,1095,EFECT CAR/DES SENSE FER-HO COSTAT VORERA,EFECT CAR/DES SIN HACERLO AL LADO ACERA,Carregar o descarregar sense fer-ho pel costat...,-,2002-01-01,9999-12-31,73.1 A,OCVV,60,E,0,Il.lm./a Sr./a Regidor/a del Districte
86,1096,EFECT CAR/DES DESTORB CIRCULAC VIAN/VEH,EFECT CAR/DES ENTORPEC CIRCULAC PEAT/VEH,Carregar o descarregar dificultant la circulac...,-,2002-01-01,9999-12-31,73.1 A,OCVV,60,E,0,Il.lm./a Sr./a Regidor/a del Districte
87,1097,EFECT CAR/DES SENSE UTILIT MITJ ADEQUATS,EFECT CAR/DES SIN UTILIZ MEDIOS ADECUAD,Carregar i descarregar sense utilitzar els mit...,-,2002-01-01,9999-12-31,73.1 A,OCVV,60,E,0,Il.lm./a Sr./a Regidor/a del Districte
88,1098,COL.LOCAR CONTENIDOR PERJUDICANT TRANSIT,COLOCAR CONTENEDOR PERJUDICANDO TRAFICO,Contenidor col.locat a la via publica fora de ...,-,2003-05-21,9999-12-31,73.1 A,OCVV,90,E,0,Il.lm./a Sr./a Regidor/a del Districte
89,1099,SENYALITZ RESERVA ESTAC SENSE LLICENCIA,SENALIZAR RESERVA ESTAC SIN LICENCIA,Senyalitzar una reserva d'estacionament o d'es...,-,2002-01-01,9999-12-31,73.1 A,OCVV,150,M,0,Il.lm./a Sr./a Regidor/a del Districte

In [117]:
# 2. Usamos la función unique para extraer los valores únicos.
# Luego, contamos su longitud usando len.
descripciones_unicas = data['Infraccio_Desc_Curta_CA'].unique()  # Extrae los valores únicos
num_descripciones_unicas = len(descripciones_unicas)  # Cuenta el número de elementos únicos
num_descripciones_unicas

588

In [118]:
# 3. Para cambiar el formato de las fechas en la columna de inicio de sanción
# a "dd/mm/aaaa", primero, usamos pd.to_datetime() para asegurarnos de que los
# datos en la columna 'Data_inici' se traten como fechas. Luego, aplicamos
# .dt.strftime('%d/%m/%Y') para convertirlas al formato "día/mes/año".

# Para ello, convertimos la columna 'Data_inici' a tipo fecha
data['Data_Inici_Vigencia'] = pd.to_datetime(data['Data_Inici_Vigencia'])

# Formateamos la columna de fecha de inicio a "dd/mm/aaaa" (día/mes/año)
data['Data_Inici_Vigencia'] = data['Data_Inici_Vigencia'].dt.strftime('%d/%m/%Y')
data.head(1)

,Infraccio_Codi,Infraccio_Desc_Curta_CA,Infraccio_Desc_Curta_ES,Infraccio_Desc_Llarga_CA,Infraccio_Desc_Llarga_ES,Data_Inici_Vigencia,Data_Fi_Vigencia,Article,Normativa,Import_Nominal_?,Tipus_Infraccio,Punts_A_Retirar,Autoritat
0,910,NO IDENTIFIC CONDUCT RESPONS INFRACCIO,NO IDENTIFIC CONDUCT RESPONS INFRACCION,NaN,-,16/03/2005,9999-12-31,77. J,LSV,301,E,0,Il.lm./a Sr./a Regidor/a del Districte

In [119]:
# 4. Verificamos si todos los valores de "Data_Fi_Vigencia" son iguales
valores_unicos = data['Data_Fi_Vigencia'].unique()
print("Valores únicos en 'Data_Fi_Vigencia':", valores_unicos)

Valores únicos en 'Data_Fi_Vigencia': ['9999-12-31']

In [120]:
# Eliminamos la columna ya que todos los valores son iguales
data.drop(columns=['Data_Fi_Vigencia'], inplace=True)

In [121]:
    data.head(1)

,Infraccio_Codi,Infraccio_Desc_Curta_CA,Infraccio_Desc_Curta_ES,Infraccio_Desc_Llarga_CA,Infraccio_Desc_Llarga_ES,Data_Inici_Vigencia,Article,Normativa,Import_Nominal_?,Tipus_Infraccio,Punts_A_Retirar,Autoritat
0,910,NO IDENTIFIC CONDUCT RESPONS INFRACCIO,NO IDENTIFIC CONDUCT RESPONS INFRACCION,NaN,-,16/03/2005,77. J,LSV,301,E,0,Il.lm./a Sr./a Regidor/a del Districte

In [122]:
# 5. Encontramos la sanción con el importe más elevado mediante max. Como extra,
# imprimimos su codigo de infracción.
importe_max_sanc = data.loc[data['Import_Nominal_?'].idxmax()]
codigo_infrac_max_sanc = importe_max_sanc['Infraccio_Codi']

print("El código de la infracción con el importe máximo es:", codigo_infrac_max_sanc)

El código de la infracción con el importe máximo es: 1444

In [123]:
# 6. Para renombrar la columna "Infraccio_Codi" a "Codi", usamos rename
data.rename(columns={'Infraccio_Codi': 'Codi'}, inplace=True)

In [124]:
    data.head(1)

,Codi,Infraccio_Desc_Curta_CA,Infraccio_Desc_Curta_ES,Infraccio_Desc_Llarga_CA,Infraccio_Desc_Llarga_ES,Data_Inici_Vigencia,Article,Normativa,Import_Nominal_?,Tipus_Infraccio,Punts_A_Retirar,Autoritat
0,910,NO IDENTIFIC CONDUCT RESPONS INFRACCIO,NO IDENTIFIC CONDUCT RESPONS INFRACCION,NaN,-,16/03/2005,77. J,LSV,301,E,0,Il.lm./a Sr./a Regidor/a del Districte

## Ejercicio 2

2.1 Cread un diccionario usando Dictionary Comprehensions tal que cada relación clave-valor sea cada una de las descripciones cortas y el valor el número de registros en que aparece esta descripción corta:

   * Las claves correspondan a la descripciones cortas en español de la sanción (**Infraccio_Desc_Curta_ES**).  
   * Sus valores correspondan al número de registros de cada descripción corta

2.2 Mostrad las 15 primeras entradas del diccionario (clave y valor) una vez lo hemos ordenado según el nombre de registros que contienen cada número (de mayor a menor).

<span style="font-family: Courier New; background-color: #82b74b; color: #000000; padding: 3px; ">SM</span> **(1 punto)**

<div style="background-color: #fcf2f2; border-color: #dfb5b4; border-left: 5px solid #dfb5b4; padding: 0.5em;">
<strong>Solución</strong>
</div>

In [125]:
# 2.1 Primero usamos value_counts() para contar las ocurrencias en
# "Infraccio_Desc_Curta_ES". Así, obtenemos claves que son descripcions y
# valores (frecuencia), que representan la cantidad de repeticiones por
# cada clave. Convertimos el resultado a diccionario
descripcion_corta_dict = data['Infraccio_Desc_Curta_ES'].value_counts().to_dict()

# 2.2 Ordenamos el diccionario por los valores (i.e., frecuencia, que es el
# segundo elemento de cada tupla mediante "key=lambda item: item[1]"),
# y seleccionamos las primeras 15 entradas. Luego, imprimimos las primeras 15
# descripciones más comunes y su número de ocurrencias

primeras_15 = sorted(descripcion_corta_dict.items(), key=lambda item: item[1],
                     reverse=True)[:15]

# Procedemos a mostrar las 15 primeras entradas ordenadas del diccionario.
print("Las 15 descripciones más frecuentes:")
for descripcion, ocurrencias in primeras_15:
    print(f"{descripcion}: {ocurrencias}")

Las 15 descripciones más frecuentes:
SUPERAR LIMITE VELOCIDAD VEHIC ESPECIAL: 6
EXCESO VELOCIDAD POR SENAL/CONDUCT/VEHIC: 5
SUPERAR LIMITE VELOCIDAD SENAL ESPECIFIC: 3
SUPERAR LIMITE VELOCIDAD NORMA GENERAL: 2
CIRCUL VEH NO AUTORIZ POR CARRIL RESERV: 2
CONDUCIR MODO MANIFIESTAMENTE TEMERARIO: 2
NO OBEDECE LUZ ROJA SEMAFORO CON PELIGRO: 2
NO IDENTIFICAR AL CONDUCTOR RESPONSABLE DE LA INFRACCION: 2
EXCESO VELOCIDAD POR RAZON DE VIA: 2
CIRCULAR INCUMPLIENDO CONDIC.DE AUTORIZACION ADM.QUE HABILIT: 1
BICICLETA HACIENDO CAMBIO SENTIDO DE LA MARCHA CON PELIGRO: 1
CONDUCIR BICI/VMP/CICLO MANERA MANIFIESTAMENTE TEMERARIA: 1
INVADIR BICICLETA SENTIDO CONTRARIO CIRCULACION CON PELIGRO: 1
CIRCULAR BICICLETA EN ENCUENTRO VIAS EN SENTIDO CONTRARIO: 1
CIRCULAR BICICLETA SENTIDO CONTRARIO EN VIA VARIAS CALZADAS: 1

## Ejercicio 3
Utilizando el dataframe obtenido en el Ejercicio 1


cread una función tal que tenga como parámetros de entrada:
* La estructura de datos (dataframe obtenido en el Ejercicio 1)
* Código de infracción
* Normativa

La función nos retornará un **booleano** que indique si la infracción que corresponde al código cumple con la Normativa (legislación) de la columna "Normativa" (LSV o OCVV o RGC).

Si no se entra ningún valor en el parámetro de normativa, que por defecto asigne el valor 'LSV'

Para mostrar el resultado, devuelve un texto completo como este : "Para la infracción con código 'código_infraccion' con fecha de vigencia 'Data_inici_vigencia' cumple la normativa 'parámetro de la normativa/no cumple la normativa". La última parte del texto dependerá si cumple o no la normativa que se ha pasado como parámetro.

<span style="font-family: Courier New; background-color: #82b74b; color: #000000; padding: 3px; ">SM</span> **(1 punto)**

<div style="background-color: #fcf2f2; border-color: #dfb5b4; border-left: 5px solid #dfb5b4; padding: 0.5em;">
<strong>Solución</strong>
</div>

In [126]:
# Cargamos de nuevo el dataframe original del ejercicio 1 (no modicado)
data = pd.read_csv('/content/drive/My Drive/Colab_Notebooks/Programación_DS/Activity_1/data/denuncies_sancions.csv', encoding='latin1', sep=';')

# Definimos la función verificar_infraccion, donde data el parametro que
# representa el dataframe, codigo_infraccion es el código concreto introducido,
# y la normativa, que tiene el valor predeterminado LSV.


def verificar_infraccion(data, codigo_infraccion, normativa='LSV'):
    # Filtramos el dataframe para obtener la fila correspondiente al
    # código de infracción. Convertimos la columna Codi y codigo_infraccion
    # a string usando astype(str) y str() para evitar errores en el filtro
    # cuando los tipos de datos no coinciden. Así, aseguramos que ambos valores
    # se comparen correctamente independientemente de sus tipos originales.

    filtro = data['Infraccio_Codi'].astype(str) == str(codigo_infraccion)
    infraccion = data[filtro]

    # Verificamos si la infracción existe en el dataframe (para evitar errores)
    if infraccion.empty:
        print(f"No se encontró ninguna infracción con el código {codigo_infraccion}.")
        return False

    # Extraemos el valor de las columna Normativa y Data_inici_vigencia
    # de la fila filtrada, al haber una única coincidencia.
    normativa_infraccion = infraccion['Normativa'].values[0]
    fecha_vigencia = infraccion['Data_Inici_Vigencia'].values[0]

    # Comparamos el valor de normativa_infraccion obtenido del dataframe con el
    # parámetro normativa proporcionado a la función.
    # Si la condición es correcta, se devuelve el mensaje del if.
    if normativa_infraccion == normativa:
        print(f"Para la infracción con código '{codigo_infraccion}' con fecha de vigencia '{fecha_vigencia}' cumple la normativa '{normativa}'.")
    else:
        print(f"Para la infracción con código '{codigo_infraccion}' con fecha de vigencia '{fecha_vigencia}' no cumple la normativa '{normativa}'.")


# Llamamos a la función con un código de infracción específico y imprimimos.
# Omitir el parámetro de normativa para usar el valor por defecto
codigo_infraccion = '910'
verificar_infraccion(data, codigo_infraccion)

Para la infracción con código '910' con fecha de vigencia '2005-03-16' cumple la normativa 'LSV'.

## Ejercicio 4
Utilizando el dataframe obtenido en el Ejercicio 1

4.1 Cread una función tal que tenga como parámetros de entrada:
* tipo_de_infracción
* puntos_a_retirar

La función devolverá todas las infracciones que cumplan que la columna "Tipus_Infraccio" sea igual al parámetro "tipo_de_infracción" y que el parámetro "puntos_a_retirar" supere el valor de la columna "Punts_A_Retirar"

Imprimid el resultado con el formato : "La infracción con código {Infraccio_Codi} ha retirado al conductor {Punts_A_Retirar} por {Infraccio_Desc_Llarga_CA}"

Realizad la prueba para el tipo de infracción M y más de 3 puntos


<span style="font-family: Courier New; background-color: #82b74b; color: #000000; padding: 3px; ">SM</span> **(1.5 puntos)**

<div style="background-color: #fcf2f2; border-color: #dfb5b4; border-left: 5px solid #dfb5b4; padding: 0.5em;">
<strong>Solución</strong>
</div>

In [127]:
# Cargamos de nuevo el dataframe original del ejercicio 1 (no modicado)
data = pd.read_csv('/content/drive/My Drive/Colab_Notebooks/Programación_DS/Activity_1/data/denuncies_sancions.csv', encoding='latin1', sep=';')

    # Filtramos el DataFrame para obtener solo las infracciones que cumplen
    # las condiciones pedidas (que el tipo de infracción coincida con el valor
    # de tipo_de_infracción y los puntos retirados sean mayores que el valor de
    # puntos_a_retirar
def filtrar_infracciones(data, tipo_de_infracción, puntos_a_retirar):
    infracciones_filtradas = data[(data['Tipus_Infraccio'] == tipo_de_infracción) & (data['Punts_A_Retirar'] > puntos_a_retirar)]

    # Comprobamos si hay infracciones filtradas
    if infracciones_filtradas.empty:
        print("No se encontraron infracciones que cumplan con los criterios.")
        return

    # Iteramos sobre cada infracción filtrada usando iterrows. Luego, extraemos
    # el código de la infracción, los puntos retirados, y la descripción
    # de la infracción en catalán. Luego, procedemos a imprimir el resultado
    # como se pide.
    for index, fila in infracciones_filtradas.iterrows():
        codigo = fila['Infraccio_Codi']
        puntos = fila['Punts_A_Retirar']
        descripcion = fila['Infraccio_Desc_Llarga_CA']
        print(f"La infracción con código {codigo} ha retirado al conductor {puntos} puntos por {descripcion}")

# Llamamos a la función con tipo de infracción 'M' y más de 1 punto a retirar
filtrar_infracciones(data, 'M', 1)

La infracción con código 1213 ha retirado al conductor 2 puntos por Circular amb exces de velocitat per raons de via.
La infracción con código 1214 ha retirado al conductor 2 puntos por Circular amb exces de velocitat per raons de senyal, conductor o vehicle.
La infracción con código 1215 ha retirado al conductor 2 puntos por Circular amb exces de velocitat per raons de senyal, conductor o vehicle (mes de 3.500 kg o mes de 9 passatgers).
La infracción con código 1216 ha retirado al conductor 4 puntos por Circular amb exces de velocitat per raons de via.
La infracción con código 1217 ha retirado al conductor 4 puntos por Circular amb exces de velocitat per raons de senyal, conductor o vehicle.
La infracción con código 1218 ha retirado al conductor 4 puntos por Circular amb exces de velocitat per raons de senyal, conductor o vehicle (mes de 3.500 kg o mes de 9 passatgers).
La infracción con código 1219 ha retirado al conductor 6 puntos por Circular amb exces de velocitat per raons de via.
La infracción con código 1220 ha retirado al conductor 6 puntos por Circular amb exces de velocitat per raons de senyal, conductor o vehicle.
La infracción con código 1221 ha retirado al conductor 6 puntos por Circular amb exces de velocitat per raons de senyal, conductor o vehicle (mes de 3.500 kg o mes de 9 passatgers).
La infracción con código 1222 ha retirado al conductor 6 puntos por Circular amb exces de velocitat per raons de via.
La infracción con código 1223 ha retirado al conductor 6 puntos por Circular amb exces de velocitat per raons de senyal, conductor o vehicle.
La infracción con código 1224 ha retirado al conductor 6 puntos por Circular amb exces de velocitat per raons de senyal, conductor o vehicle (mes de 3.500 kg o mes de 9 passatgers).
La infracción con código 1229 ha retirado al conductor 2 puntos por Circular amb exces de velocitat per raons de via (mes de 3.500 kg o mes de 9 passatgers).
La infracción con código 1230 ha retirado al conductor 4 puntos por Circular amb exces de velocitat per raons de via (mes de 3.500 kg o mes de 9 passatgers).
La infracción con código 1231 ha retirado al conductor 6 puntos por Circular amb exces de velocitat per raons de via (mes de 3.500 kg o mes de 9 passatgers).
La infracción con código 1232 ha retirado al conductor 6 puntos por Circular amb exces de velocitat per raons de via (mes de 3.500 kg o mes de 9 passatgers).
La infracción con código 1304 ha retirado al conductor 6 puntos por Conduir un vehicle de dues rodes de manera manifestament temeraria.
La infracción con código 1305 ha retirado al conductor 6 puntos por Conduir un vehicle de manera manifestament temeraria.
La infracción con código 1306 ha retirado al conductor 6 puntos por Llencar a la via publica o als seus voltants un objecte que pugui ocasionar un incendi o un accident de circulacio.
La infracción con código 1327 ha retirado al conductor 4 puntos por Circular amb un menor d'edat d'alcada igual o inferior a 135 centimetres amb un sistema de retencio infantil homologat a l'efecte en el seient davanter del vehicle en suposits no autoritzats
La infracción con código 1337 ha retirado al conductor 4 puntos por Circular amb un menor edat  alcada igual o inferior a 135 centimetres sense utilitzar, o no fer-ho de forma adequada, un sistema de retencio infantil homologat a efecte
La infracción con código 1340 ha retirado al conductor 6 puntos por Envair el sentit contrari de la circulacio amb perill.
La infracción con código 1366 ha retirado al conductor 6 puntos por Entaular competencia de velocitat entre vehicles a la via publica o zona d'us public.
La infracción con código 1386 ha retirado al conductor 4 puntos por Avancar en revolts, canvis de rasant i en llocs de visibilitat reduida.
La infracción con código 1395 ha retirado al conductor 6 puntos por Excedir en mes d'un 50% els temps de conduccio establerts en la legislacio sobre transports terrestres.
La infracción con código 1396 ha retirado al conductor 6 puntos por Minorar en mes d'un 50% els periodes de descans establerts en la legislacio sobre transports terrestres.
La infracción con código 1401 ha retirado al conductor 4 puntos por Circular sense utilitzar, degudament cordats, el conductor el cinturo de seguretat.
La infracción con código 1402 ha retirado al conductor 4 puntos por No utilitzar el conductor casc de proteccio circulant en ciclomotor.
La infracción con código 1403 ha retirado al conductor 4 puntos por No utilitzar el conductor casc de proteccio circulant en motocicleta.
La infracción con código 1408 ha retirado al conductor 4 puntos por No utilitzar el conductor casc de proteccio circulant en vehicles de tres rodes o quadricicles, o vehicles especials tipus quad.
La infracción con código 1444 ha retirado al conductor 6 puntos por Conduir vehicles  que portin  instal.lats inhibidors de radar o cinemometres  o altres mecanismes per interferir en correcte  funcionament sistemes  vigilancia de transit
La infracción con código 1446 ha retirado al conductor 4 puntos por No utilitzar el conductor del vehicle que n'ha sortit i ocupa la calcada o el voral de la via, una armilla reflectora de visibilitat alta
La infracción con código 1474 ha retirado al conductor 6 puntos por Circular per una placa / glorieta / trobada de vies, en sentit contrari de l'estipulat.
La infracción con código 1485 ha retirado al conductor 6 puntos por Circular en sentit contrari de l'estipulat en una via dividida en mes d'una calcada.
La infracción con código 1486 ha retirado al conductor 4 puntos por Circular darrere d'un altre vehicle sense mantenir la distancia que li permeti aturar-se, sense col.lisionar, en cas de frenada brusca del que el precedeix
La infracción con código 1503 ha retirado al conductor 4 puntos por Desobeir els SENYALS i/o les ORDRES D'UN AGENT que regula la circulacio AMB PERILL.
La infracción con código 1504 ha retirado al conductor 4 puntos por No obeir el conductor d'un ciclomotor o motocicleta el LLUM VERMELL d'un semafor AMB PERILL.
La infracción con código 1505 ha retirado al conductor 4 puntos por No obeir el conductor d'un vehicle el LLUM VERMELL d'un semafor AMB PERILL.
La infracción con código 1506 ha retirado al conductor 4 puntos por No cedir el pas en interseccio regulada amb senyal de CEDIU EL PAS O STOP obligant a la resta de conductor a fer maniobres brusques AMB RISC DE COL.LISIO.
La infracción con código 1549 ha retirado al conductor 4 puntos por No utilitzar el conductor casc de proteccio homologat i certificat.
La infracción con código 1550 ha retirado al conductor 4 puntos por No utilitzar el conductor adequadament el casc de proteccio (especifiqueu-ne l'us inadequat).
La infracción con código 1576 ha retirado al conductor 4 puntos por Avancar un vehicle a bicicleta o ciclomotor posant en perill o entorpint a ciclistes que circulen en sentit contrari, inclos arcen
La infracción con código 1583 ha retirado al conductor 4 puntos por No respectar la prioritat de pas dels ciclistes amb perill.
La infracción con código 1584 ha retirado al conductor 4 puntos por Retrocedir en una via on no estigui autoritzat amb perill.
La infracción con código 1585 ha retirado al conductor 3 puntos por Conduir un vehicle utilitzant dispositius de telefonia mobil.
La infracción con código 1591 ha retirado al conductor 3 puntos por Conduir un vehicle a motor utilitzant auriculars connectats a aparells receptors o reproductors de so.
La infracción con código 1620 ha retirado al conductor 3 puntos por Conduir utilitzant manualment navegadors
La infracción con código 1650 ha retirado al conductor 3 puntos por Conduir un vehicle que portin mecanismes de deteccio de radars o cinemometres
La infracción con código 1686 ha retirado al conductor 6 puntos por Avancar un vehicle a bicicleta o ciclomotor sense deixar una amplada de seguretat d'almenys 1,5 metres
La infracción con código 1687 ha retirado al conductor 6 puntos por Conduir un vehicle subjectant amb la ma dispositius de telefonia mobil
La infracción con código 1688 ha retirado al conductor 3 puntos por Conduir un vehicle utilitzant dispositius de telefonia mobil mantenint-los ajustats entre el casc de proteccio i el cap de usuari
La infracción con código 3281 ha retirado al conductor 4 puntos por Conduir un vehicle. Taxa alcohol en aire expirat superior a 0,15 mg/l, conductor professional, servei public, mercaderies perilloses, transports especials, novells...
La infracción con código 3282 ha retirado al conductor 4 puntos por Conductor reincident. Conduir un vehicle. Taxa d'alcohol en aire expirat superior a 0,15 mg/l, conductor professional, servei public, mercaderies perilloses, transports especials, novells
La infracción con código 3284 ha retirado al conductor 4 puntos por Conduir un vehicle. Taxa d'alcohol en aire expirat superior a 0,25 mg/l
La infracción con código 3285 ha retirado al conductor 4 puntos por Conductor reincident. Conduir un vehicle. Taxa d'alcohol en aire expirat superior a 0,25 mg/l
La infracción con código 3287 ha retirado al conductor 6 puntos por Conduir un vehicle. Taxa d'alcohol en aire expirat superior a 0,30 mg/l, conductor professional, servei public, mercaderies perilloses, transports especials, novells...
La infracción con código 3288 ha retirado al conductor 6 puntos por Conductor reincident. Conduir un vehicle. Taxa d'alcohol en aire expirat superior a 0,30 mg/l, conductor professional, servei public, mercaderies perilloses, transports especials, novells
La infracción con código 3290 ha retirado al conductor 6 puntos por Conduir un vehicle. Taxa d'alcohol en aire expirat superior a 0,50 mg/l
La infracción con código 3291 ha retirado al conductor 6 puntos por Conductor reincident. Conduir un vehicle. Taxa d'alcohol en aire expirat superior a 0,50 mg/l
La infracción con código 3293 ha retirado al conductor 6 puntos por No sotmetre's a les proves de deteccio alcoholica, el conductor d'un vehicle
La infracción con código 3296 ha retirado al conductor 6 puntos por Conduir un vehicle amb presencia de drogues a l'organisme
La infracción con código 3299 ha retirado al conductor 6 puntos por No sotmetre's, el conductor un vehicle  a les proves per a la deteccio de drogues a organisme

## Ejercicio 5
Os pedimos lo siguiente:

5.1 Obtener la infracción con el importe nominal (Import_Nominal) más alto.

5.2. Implementar una función que reciba como parámetro de entrada una palabra y que compruebe si la palabra aparece en la columna "Infraccio_Desc_curta_ES". Que muestre todas las infracciones con la coincidencia.

5.3 Utilizando una dict comprehension crea un diccionario donde las claves sean los códigos de infracción (Infraccio_Codi) y los valores sean las descripciones largas de la infracción en catalán (Infraccio_Desc_Llarga_CA), pero solo para aquellas infracciones en las que se hayan retirado puntos al conductor (Punts_A_Retirar > 0)

<span style="font-family: Courier New; background-color: #82b74b; color: #000000; padding: 3px; ">SM</span> **(1.5 puntos)**

<div style="background-color: #fcf2f2; border-color: #dfb5b4; border-left: 5px solid #dfb5b4; padding: 0.5em;">
<strong>Solución</strong>
</div>

In [128]:
# 5.1 Encontramos la infracción con el importe nominal más alto
# mediante .idxmax. Luego, vamos a su fila mediante .loc y la mostramos.
idx_importe_max = data['Import_Nominal_?'].idxmax()
infraccion_importe_max = data.loc[idx_importe_max]
infraccion_importe_max

Infraccio_Codi                                                           1444
Infraccio_Desc_Curta_CA     PORTAR INSTAL.LAT  INHIBIDORS RADAR,CINEMOMETR...
Infraccio_Desc_Curta_ES     LLEVAR INSTALADO INHIBIDORES RADAR,CINEMOMETRO...
Infraccio_Desc_Llarga_CA    Conduir vehicles  que portin  instal.lats inhi...
Infraccio_Desc_Llarga_ES                                                    -
Data_Inici_Vigencia                                                2022-03-21
Data_Fi_Vigencia                                                   9999-12-31
Article                                                                    77
Normativa                                                                 LSV
Import_Nominal_?                                                         6000
Tipus_Infraccio                                                             M
Punts_A_Retirar                                                             6
Autoritat                         Il.lm./a Sr./a  Primer Tinent/a d'Alcaldia.
Name: 259, dtype: object

In [129]:
# 5.2 Definimos una función que busque infracciones por palabra clave en
# "Infraccio_Desc_Curta_ES". Para ello, es necesario poner de parametro un
# presunto dataframe.
def filtrar_infraccion(df_infr_filt: pd.DataFrame, palabra: str) -> pd.DataFrame:
    # Guardamos toda la columna de "Infraccio_Desc_Curta_ES" de "descripcion".
    # Luego, filtramos las infracciones que contienen "palabra" en "descripción"
    # case=False indica que la búsqueda no distingue entre casings.
    # na=False ignora los valores nulos.
    # regex=False sirve para tratar la palabra como texto literal
    descripcion = df_infr_filt['Infraccio_Desc_Curta_ES']
    resultados = df_infr_filt[descripcion.str.contains(palabra, case=False, na=False, regex=False)]

    # Mostramos las coincidencias
    if resultados.empty:
        print(f"No se encontraron infracciones que contengan la palabra '{palabra}'.")
    else:
        return resultados

# Llamamos a la función
filtrar_infraccion(data, "Libertad")

,Infraccio_Codi,Infraccio_Desc_Curta_CA,Infraccio_Desc_Curta_ES,Infraccio_Desc_Llarga_CA,Infraccio_Desc_Llarga_ES,Data_Inici_Vigencia,Data_Fi_Vigencia,Article,Normativa,Import_Nominal_?,Tipus_Infraccio,Punts_A_Retirar,Autoritat
279,1466,CONDUIR VEHICLE SENSE LLIBERTAT MOVIMENT,CONDUCIR VEHICULO SIN LIBERTAD MOVIMIENT,Conduir un vehicle sense mantenir la propia ll...,-,2010-05-25,9999-12-31,18. 1,RGC,200,M,0,Il.lm./a Sr./a Regidor/a del Districte

In [130]:
# 5.3 Creamos un diccionario donde las claves son los códigos de infracción
# y los valores son las descripciones largas. Luego iteramos sobre cada fila
# del dataframe y guardamos aquellas filas en las que "Punts_A_Retirar" > 0
# puntos a retirar mayores que cero.
infracciones_dict = {row['Infraccio_Codi']: row['Infraccio_Desc_Llarga_CA']
    for index, row in data.iterrows() if row['Punts_A_Retirar'] > 0}

# Mostramos el diccionario completo mediante el bucle for, que itera sobre los
# elementos del diccionario.
print("Diccionario de infracciones con puntos a retirar:")
for codi, descripcion in infracciones_dict.items():
    print(f"Código: {codi}; Descripción: {descripcion}")

Diccionario de infracciones con puntos a retirar:
Código: 1213; Descripción: Circular amb exces de velocitat per raons de via.
Código: 1214; Descripción: Circular amb exces de velocitat per raons de senyal, conductor o vehicle.
Código: 1215; Descripción: Circular amb exces de velocitat per raons de senyal, conductor o vehicle (mes de 3.500 kg o mes de 9 passatgers).
Código: 1216; Descripción: Circular amb exces de velocitat per raons de via.
Código: 1217; Descripción: Circular amb exces de velocitat per raons de senyal, conductor o vehicle.
Código: 1218; Descripción: Circular amb exces de velocitat per raons de senyal, conductor o vehicle (mes de 3.500 kg o mes de 9 passatgers).
Código: 1219; Descripción: Circular amb exces de velocitat per raons de via.
Código: 1220; Descripción: Circular amb exces de velocitat per raons de senyal, conductor o vehicle.
Código: 1221; Descripción: Circular amb exces de velocitat per raons de senyal, conductor o vehicle (mes de 3.500 kg o mes de 9 passatgers).
Código: 1222; Descripción: Circular amb exces de velocitat per raons de via.
Código: 1223; Descripción: Circular amb exces de velocitat per raons de senyal, conductor o vehicle.
Código: 1224; Descripción: Circular amb exces de velocitat per raons de senyal, conductor o vehicle (mes de 3.500 kg o mes de 9 passatgers).
Código: 1229; Descripción: Circular amb exces de velocitat per raons de via (mes de 3.500 kg o mes de 9 passatgers).
Código: 1230; Descripción: Circular amb exces de velocitat per raons de via (mes de 3.500 kg o mes de 9 passatgers).
Código: 1231; Descripción: Circular amb exces de velocitat per raons de via (mes de 3.500 kg o mes de 9 passatgers).
Código: 1232; Descripción: Circular amb exces de velocitat per raons de via (mes de 3.500 kg o mes de 9 passatgers).
Código: 1304; Descripción: Conduir un vehicle de dues rodes de manera manifestament temeraria.
Código: 1305; Descripción: Conduir un vehicle de manera manifestament temeraria.
Código: 1306; Descripción: Llencar a la via publica o als seus voltants un objecte que pugui ocasionar un incendi o un accident de circulacio.
Código: 1327; Descripción: Circular amb un menor d'edat d'alcada igual o inferior a 135 centimetres amb un sistema de retencio infantil homologat a l'efecte en el seient davanter del vehicle en suposits no autoritzats
Código: 1337; Descripción: Circular amb un menor edat  alcada igual o inferior a 135 centimetres sense utilitzar, o no fer-ho de forma adequada, un sistema de retencio infantil homologat a efecte
Código: 1340; Descripción: Envair el sentit contrari de la circulacio amb perill.
Código: 1366; Descripción: Entaular competencia de velocitat entre vehicles a la via publica o zona d'us public.
Código: 1386; Descripción: Avancar en revolts, canvis de rasant i en llocs de visibilitat reduida.
Código: 1395; Descripción: Excedir en mes d'un 50% els temps de conduccio establerts en la legislacio sobre transports terrestres.
Código: 1396; Descripción: Minorar en mes d'un 50% els periodes de descans establerts en la legislacio sobre transports terrestres.
Código: 1401; Descripción: Circular sense utilitzar, degudament cordats, el conductor el cinturo de seguretat.
Código: 1402; Descripción: No utilitzar el conductor casc de proteccio circulant en ciclomotor.
Código: 1403; Descripción: No utilitzar el conductor casc de proteccio circulant en motocicleta.
Código: 1408; Descripción: No utilitzar el conductor casc de proteccio circulant en vehicles de tres rodes o quadricicles, o vehicles especials tipus quad.
Código: 1444; Descripción: Conduir vehicles  que portin  instal.lats inhibidors de radar o cinemometres  o altres mecanismes per interferir en correcte  funcionament sistemes  vigilancia de transit
Código: 1446; Descripción: No utilitzar el conductor del vehicle que n'ha sortit i ocupa la calcada o el voral de la via, una armilla reflectora de visibilitat alta
Código: 1474; Descripción: Circular per una placa / glorieta / trobada de vies, en sentit contrari de l'estipulat.
Código: 1485; Descripción: Circular en sentit contrari de l'estipulat en una via dividida en mes d'una calcada.
Código: 1486; Descripción: Circular darrere d'un altre vehicle sense mantenir la distancia que li permeti aturar-se, sense col.lisionar, en cas de frenada brusca del que el precedeix
Código: 1503; Descripción: Desobeir els SENYALS i/o les ORDRES D'UN AGENT que regula la circulacio AMB PERILL.
Código: 1504; Descripción: No obeir el conductor d'un ciclomotor o motocicleta el LLUM VERMELL d'un semafor AMB PERILL.
Código: 1505; Descripción: No obeir el conductor d'un vehicle el LLUM VERMELL d'un semafor AMB PERILL.
Código: 1506; Descripción: No cedir el pas en interseccio regulada amb senyal de CEDIU EL PAS O STOP obligant a la resta de conductor a fer maniobres brusques AMB RISC DE COL.LISIO.
Código: 1549; Descripción: No utilitzar el conductor casc de proteccio homologat i certificat.
Código: 1550; Descripción: No utilitzar el conductor adequadament el casc de proteccio (especifiqueu-ne l'us inadequat).
Código: 1576; Descripción: Avancar un vehicle a bicicleta o ciclomotor posant en perill o entorpint a ciclistes que circulen en sentit contrari, inclos arcen
Código: 1583; Descripción: No respectar la prioritat de pas dels ciclistes amb perill.
Código: 1584; Descripción: Retrocedir en una via on no estigui autoritzat amb perill.
Código: 1585; Descripción: Conduir un vehicle utilitzant dispositius de telefonia mobil.
Código: 1591; Descripción: Conduir un vehicle a motor utilitzant auriculars connectats a aparells receptors o reproductors de so.
Código: 1620; Descripción: Conduir utilitzant manualment navegadors
Código: 1650; Descripción: Conduir un vehicle que portin mecanismes de deteccio de radars o cinemometres
Código: 1686; Descripción: Avancar un vehicle a bicicleta o ciclomotor sense deixar una amplada de seguretat d'almenys 1,5 metres
Código: 1687; Descripción: Conduir un vehicle subjectant amb la ma dispositius de telefonia mobil
Código: 1688; Descripción: Conduir un vehicle utilitzant dispositius de telefonia mobil mantenint-los ajustats entre el casc de proteccio i el cap de usuari
Código: 3281; Descripción: Conduir un vehicle. Taxa alcohol en aire expirat superior a 0,15 mg/l, conductor professional, servei public, mercaderies perilloses, transports especials, novells...
Código: 3282; Descripción: Conductor reincident. Conduir un vehicle. Taxa d'alcohol en aire expirat superior a 0,15 mg/l, conductor professional, servei public, mercaderies perilloses, transports especials, novells
Código: 3284; Descripción: Conduir un vehicle. Taxa d'alcohol en aire expirat superior a 0,25 mg/l
Código: 3285; Descripción: Conductor reincident. Conduir un vehicle. Taxa d'alcohol en aire expirat superior a 0,25 mg/l
Código: 3287; Descripción: Conduir un vehicle. Taxa d'alcohol en aire expirat superior a 0,30 mg/l, conductor professional, servei public, mercaderies perilloses, transports especials, novells...
Código: 3288; Descripción: Conductor reincident. Conduir un vehicle. Taxa d'alcohol en aire expirat superior a 0,30 mg/l, conductor professional, servei public, mercaderies perilloses, transports especials, novells
Código: 3290; Descripción: Conduir un vehicle. Taxa d'alcohol en aire expirat superior a 0,50 mg/l
Código: 3291; Descripción: Conductor reincident. Conduir un vehicle. Taxa d'alcohol en aire expirat superior a 0,50 mg/l
Código: 3293; Descripción: No sotmetre's a les proves de deteccio alcoholica, el conductor d'un vehicle
Código: 3296; Descripción: Conduir un vehicle amb presencia de drogues a l'organisme
Código: 3299; Descripción: No sotmetre's, el conductor un vehicle  a les proves per a la deteccio de drogues a organisme

## Ejercicio 6
En este ejericio practicaréis expresiones regulares, para ello os pedimos:

6.1. Utiliza expresiones regulares para encontrar todas las infracciones cuya descripción larga en catalán (Infraccio_Desc_Llarga_CA) mencione cualquier forma de la palabra 'velocitat' (por ejemplo, 'velocitat', 'velocitats', etc.). Muestra las filas que correspondan a esas infracciones.
   
6.2. Utiliza expresiones regulares para encontrar todas las infracciones cuya descripción corta en español (Infraccio_Desc_Curta_ES) mencione algún número, sin importar su formato (por ejemplo, 100, 2000, 10.000, etc.). Muestra las filas correspondientes a esas infracciones.

6.3. Utiliza expresiones regulares para encontrar todas las infracciones cuya descripción corta en español (Infraccio_Desc_Curta_ES) mencione términos: ciclistas, arcen, cruce, estacionar. Muestra las filas correspondientes a esas infracciones
   
<span style="font-family: Courier New; background-color: #82b74b; color: #000000; padding: 3px; ">SM</span> **(1.5 puntos)**

<div style="background-color: #fcf2f2; border-color: #dfb5b4; border-left: 5px solid #dfb5b4; padding: 0.5em;">
<strong>Solución</strong>
</div>

In [131]:
# 6.1 Utilizamos str.contains() para buscar la palabra "velocitat" en la columna
# "Infraccio_Desc_Llarga_CA" sin importar el casing y ignorando los nulos.
# La expresión regular es "velocitat", mientras que la secuencia de escape \w*
# (que en este caso coincide con cero o más caracteres alfanuméricos)
# admite cualquier forma de la palabra (aunque no parece ser necesario para este
# caso). Además, el uso de la r asegura que las secuencias de escape se lean
# como son de forma nativa en vez de como texto literal.
descrip_larga = data['Infraccio_Desc_Llarga_CA']
coincidencias_velocitat = descrip_larga.str.contains(r'velocitat\w*', case=False, na=False)
infracciones_velocitat = descrip_larga[coincidencias_velocitat]
print("Infracciones que mencionan 'velocitat':")
print(infracciones_velocitat)

Infracciones que mencionan 'velocitat':
122    No reduir la velocitat en carrers d'un sol car...
123      No reduir la velocitat en carrers sense vorera.
124    No reduir la velocitat en una situacio de gran...
125    No reduir la velocitat en cas de pluja, neu, p...
126    No reduir la velocitat en cas de mal estat del...
127    No reduir la velocitat a causa de l'estretor d...
128     No reduir la velocitat en carrers d'una zona 30.
129    No reduir la velocitat en carrers de prioritat...
150    Circular amb exces de velocitat per raons de via.
151    Circular amb exces de velocitat per raons de s...
152    Circular amb exces de velocitat per raons de s...
153    Circular amb exces de velocitat per raons de via.
154    Circular amb exces de velocitat per raons de s...
155    Circular amb exces de velocitat per raons de s...
156    Circular amb exces de velocitat per raons de via.
157    Circular amb exces de velocitat per raons de s...
158    Circular amb exces de velocitat per raons de s...
159    Circular amb exces de velocitat per raons de via.
160    Circular amb exces de velocitat per raons de s...
161    Circular amb exces de velocitat per raons de s...
162    Circular amb exces de velocitat per raons de via.
163    Circular amb exces de velocitat per raons de s...
164    Circular amb exces de velocitat per raons de s...
165    Circular amb exces de velocitat per raons de v...
166    Circular amb exces de velocitat per raons de v...
167    Circular amb exces de velocitat per raons de v...
168    Circular amb exces de velocitat per raons de v...
169    Circular amb exces de velocitat per raons de v...
171    Circular en patinet, monopati o aparell simila...
207    Circular a velocitat anormalment reduida sense...
208    Reduccio brusca i imprudent de la velocitat se...
209    Entaular competencia de velocitat entre vehicl...
314    Circular amb un vehicle sense moderar la veloc...
385    Circular en bicicleta pel carril bici a una ve...
389    Circular un vehicle darrera d'una bicicleta se...
461    Circular en bicicleta sense reduir la velocita...
484    Circular amb un vehicle de mobilitat personal ...
490    Circular amb un vehicle de mobilitat personal ...
491    Circular amb un vehicle de mobilitat personal ...
492    Circular amb un vehicle de mobilitat personal ...
494    Circular amb un vehicle de mobilitat personal ...
495    Circular amb un vehicle de mobilitat personal ...
496    Circular amb un vehicle de mobilitat personal ...
500    Circular amb un cicle de mes de dues rodes del...
Name: Infraccio_Desc_Llarga_CA, dtype: object

In [132]:
# 6.2 Para encontrar infracciones que contienen números, buscamos cualquier
# número en la columna "Infraccio_Desc_Curta_ES".
# La expresión regular "\d+" busca una o más cifras. Usamos otra vez na=False
# para manejar los valores nulos para evitar errores.
descrip_corta = data['Infraccio_Desc_Curta_ES']
coincidencias_numeros = descrip_corta.str.contains(r'\d+', na=False)
infracciones_numeros = descrip_corta[coincidencias_numeros]
print("Infracciones que contienen números:")
print(infracciones_numeros)

Infracciones que contienen números:
12              PARAR CALL/PLAZ S/ACERAS MENOS 1M FACHAD
47     ESTAC DIST INFER 5 M ALINEACIO BORDILLO CALLE ...
60               ESTAC MAS 8 DIAS CONSECUTIV MISMO LUGAR
71              ESTAC MOTO/CICLOMOT ACERA INFERIOR A 3 M
72               ESTAC MOTO/CICLOM MAS 50 CM LINEA ACERA
                             ...
603    CONDUCTOR MENOR NOVEL TAXA ALCOHOL HASTA 0,15 ...
604    CONDUCTOR MENOR NOVEL REINCIDENTE TAXA ALCOHOL...
605    CONDUCTOR MENOR TAXA ALCOHOL HASTA 0,25 MG/L S...
606    CONDUCTOR MENOR REINCIDENTE TAXA ALCOHOL HASTA...
607    CONDUC MENOR CICLO/ MAS 2 RUEDA/VMP, TAXA ALCO...
Name: Infraccio_Desc_Curta_ES, Length: 110, dtype: object

In [133]:
# 6.3 Buscamos varios los términos ciclistas, arcen, cruce, y estacionar en la
# columna "Infraccio_Desc_Curta_ES". Usamos la expresión regular
# 'ciclistas|arcen|cruce|estacionar', donde el operador '|' actúa como un OR,
# lo que nos permite que se capture cualquiera de los términos.
descrip_corta = data['Infraccio_Desc_Curta_ES']
terminos = r'ciclistas|arcen|cruce|estacionar'
coincidencias_terminos = descrip_corta.str.contains(terminos, case=False, na=False)
infrac_terminos = descrip_corta[coincidencias_terminos]
print("Infracciones que mencionan los términos específicos:")
print(infrac_terminos)

Infracciones que mencionan los términos específicos:
14                          PARARSE EN PASO DE CICLISTAS
17                              PARARSE EN ACERA O ARCEN
21                       PARARSE EN CRUCE O INTERSECCION
28                       ESTACIONAR EN CARRIL BICICLETAS
35                       ESTACIONAR EN PASO DE CICLISTAS
36                      ESTACIONAR EN PASO PARA PEATONES
38                              ESTACIONAR EN CARRIL BUS
39               ESTACIONAR EN PARADA TRANSPORTE PUBLICO
40                        ESTACIONAR EN ZONAS RESERVADAS
41                    ESTACIONAR EN CRUCE O INTERSECCION
45                           ESTACIONAR EN PLENA CALZADA
48                                   ESTACIONAR EN ACERA
49                  ESTACIONAR EN ANDEN/PARTERRE/REFUGIO
50                 ESTACIONAR EN PASEO CENTRAL O LATERAL
52                 ESTACIONAR AL LADO DE ANDEN O REFUGIO
97               ESTACIONAR VEHICULO PARA VENTA/ALQUILER
98              ESTACIONAR VEHICULO CON FIN PUBLICITARIO
100      ESTACIONAR EN ZONA AZUL SIN ACREDITACION VALIDA
101    ESTACIONAR CARGA/DESCARGA SIN ACREDITACION VALIDA
102    ESTACIONAR EN ZONA DISCAPACITADOS SIN ACREDITA...
103    ESTACIONAR ZONA RESERVADA SIN ACREDITACION VALIDA
109                 ESTACIONAR IMPIDIENDO LA CIRCULACION
112                                  ESTACIONAR EN ANDEN
130    ESTACIONAR EN REBAJE DE ACEERA PARA PERSONA DI...
132    ESTACIONAR MOTO/CICLOMOT ACERA DELANTE ZONA RE...
138    ESTACIONAR MOTO/CICLOM EN ACERA SIN ESPACIO 3 ...
139    ESTACIONAR EN EL SENTIDO CONTRARIO DE LA CIRCU...
143    ESTACIONAR AUTOCAR DONDE LO PROHIBE LA SENAL C...
145    ESTACIONAR EN ZONA DE RECARGA DE VEHICULOS ELE...
146    ESTACIONAR VEHICULO ELECTRICO EN Z RECARGA EXC...
147    ESTACIONAR AUTOCAR DONDE PROHIBE SENYAL CORRES...
148    ESTACIONAR VEH ELECTRICO ZONA RECARGA RESERV P...
149    ESTACIONAR AUTOCAR ZONA RESERVADA AUTOCAR SIN ...
202             CIRC ARCEN VEHIC NO AUTORIZ SIN EMERGENC
287             CIRC CARRIL ADICIONAL SIN LUCES DE CRUCE
311              NO RESPETAR PRIORIDAD PEATONES EN ARCEN
336             NO UTILIZAR LUCES DE CRUCE CASOS OBLIGAT
359                       CIRCULAR MARCHA ATRAS EN CRUCE
364                      NO RESPETAR PRIORIDAD CICLISTAS
365                  GIRAR SIN DAR PRIORIDAD A CICLISTAS
368                 ADELANTAR INTERSEC CON VIA CICLISTAS
377    ESTACIONAR CON RIESGO A CIRCULACION/PEATONES C...
379    ESTACIONAR CARRIL T PUBLIC GRAVE PERTURBAC/RIE...
393          ESTACIONAR BICICLETA EN LUGAR NO AUTORIZADO
466    ESTACIONAR BICICLETA DELANTE ZONAS APARCAMIENT...
467    ESTACIONAR BICICLETA EN ACERA IMPIDIENDO PASO ...
470    PARAR O ESTACIONAR VEHICULO MOTOR EN CARRILS/V...
521         Estacionar VMP comercial A/B lugar reservado
536      ESTACIONAR LUGAR NO AUTORIZADO CICLO 2R C1 O C2
539              ESTACIONAR VMP TIPO A/B LUGAR RESERVADO
540       ESTACIONAR VMP TIPO A/B IMPEDIENDO PASO PEATON
Name: Infraccio_Desc_Curta_ES, dtype: object

## Ejercicio 7. Proyecto
**Ejercicio: Gestión de una lista de infracciones pendientes**

**Enunciado**:

Crea un programa que mantenga una lista de infracciones pendientes de tramitar. Solamente contendrá códigos de infracción (1 columna)

*   Comienza con una lista vacía.
*   Pide al usuario que añada infracciones (códigos de infracción) a la lista.
*   Permite al usuario quitar una infracción de la lista si ya ha sido tramitada.
*   Muestra la lista de infracciones pendientes después de cada operación.


**Detalles**:

*   El programa ofrecerá (pedirá al usuario) 3 opciones: Añadir infracción, eliminiar infracción y salir.
*   Si elige la opción Añadir, el programa debe permitir añadir múltiples infracciones hasta que el usuario decida terminar.
*   Si elige la opción Eliminiar, el usuario puede eliminar una infracción especificando su código. Si el código de infracción a eliminar no está en la lista, el programa debe notificar al usuario.
*   Si elige la opción Salir, el programa finaliza.

<span style="font-family: Courier New; background-color: #82b74b; color: #000000; padding: 3px; ">SM</span> **(1.5 puntos)**

<div style="background-color: #fcf2f2; border-color: #dfb5b4; border-left: 5px solid #dfb5b4; padding: 0.5em;">
<strong>Solución</strong>
</div>

In [134]:
def gestionar_infrac():
    # Empezamos con crear una lista vacía para manejar las infracciones.
    infrac_pendientes = []

    # Ahora creamos un bucle infinito para manejar las opciones resaltadas.
    while True:
        print("1. Añadir infracción")
        print("2. Eliminar infracción")
        print("3. Salir")
        opcion = input("Elige una opción (1, 2, 3) --> ")

        # Si el usuario introduce 1, continuamos por aquí
        if opcion == "1":

            # Añadimos infracción mediante .append.
            # Si se escribe salir, se termina el programa.
            while True:
                codigo = input("Introduce código de infracción. Escribe salir para terminar --> ")
                if codigo == 'salir':
                    break
                infrac_pendientes.append(codigo)

        # Si el usuario introduce 2, continuamos por aquí
        elif opcion == "2":

            # Eliminamos la infracción ya introducida por el usuario
            # mediante .remove
            codigo = input("Código de infracción a eliminar --> ")
            if codigo in infrac_pendientes:
                infrac_pendientes.remove(codigo)
            else:
                print("No está en la lista.")

        # Si el usuario introduce 3, continuamos por aquí.
        # Imprimimos "Saliendo" y terminamos el programa.
        elif opcion == "3":
            print("Saliendo.")
            break

        # Mostramos la lista de infracciones tras cada operación
        print("Infracciones pendientes --> ", infrac_pendientes)

# Llamamos a la función para empezar a ejecutar el programa desde aquí.
gestionar_infrac()

1. Añadir infracción
2. Eliminar infracción
3. Salir
Elige una opción (1, 2, 3) --> 3
Saliendo.

Referencias

Universitat Oberta de Catalunya. (2020). Programación para la ciencia de datos. Disponible en: https://aula.uoc.edu/courses/42513

Universitat Oberta de Catalunya. (2021). Estructuras de datos avanzadas. Disponible en: https://aula.uoc.edu/courses/42513

Stack Overflow. (n.d.). Stack Overflow. https://stackoverflow.com/

Programiz. (n.d.). Python RegEx: re.match(), re.search(), re.findall() with Example. Programiz. https://www.programiz.com/python-programming/regex

The pandas development team. (2023). pandas documentation (v2.0). https://pandas.pydata.org/pandas-docs/stable/

The pandas development team. (2023). pandas documentation (v2.0). https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.html

The pandas development team. (2023). pandas documentation (v2.0). https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.str.contains.html

The pandas development team. (2023). pandas documentation (v2.0). https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.idxmax.html

The pandas development team. (2023). pandas documentation (v2.0). https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.html

The pandas development team. (2023). pandas documentation (v2.0). https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html

The pandas development team. (2023). pandas documentation (v2.0). https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.astype.html

The pandas development team. (2023). pandas documentation (v2.0). https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.drop.html

The pandas development team. (2023). pandas documentation (v2.0). https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.rename.html

Uso de pd.to_datetime() para conversión a tipo fecha: The pandas development team. (2023). pandas documentation (v2.0). https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.to_datetime.html

Python Software Foundation. (2024). Python Language Reference, version 3.11. https://docs.python.org/3/reference/

Python Software Foundation. (n.d.). Regular Expression HOWTO. Python.org. https://docs.python.org/3/howto/regex.html#regex-howto

Python Software Foundation. (n.d.). strftime() and strptime() format codes. Python.org. https://docs.python.org/3/library/datetime.html#strftime-and-strptime-format-codes

Python Software Foundation. (n.d.). Built-in Functions: print(). Python.org. https://docs.python.org/3/library/functions.html#print

Python Software Foundation. (n.d.). f-strings (formatted string literals). Python.org. https://docs.python.org/3/reference/lexical_analysis.html#f-strings

Python Software Foundation. (n.d.). Compound statements: if, elif, and else. Python.org. https://docs.python.org/3/reference/compound_stmts.html#if

Python Software Foundation. (n.d.). Dictionaries. Python.org. https://docs.python.org/3/tutorial/datastructures.html#dictionaries